@startuml SequenceDiagram
skinparam classAttributeIconSize 0
skinparam style strictuml
participant ByteCeps
participant ":Parser"
participant ":HelpMenuManager"
participant HelpStrings
participant HelpValidator


activate ByteCeps
ByteCeps -> ":Parser": parseInput(userInput)
activate ":Parser"
ByteCeps <-- ":Parser":
deactivate ":Parser"
ByteCeps -> ":HelpMenuManager": execute(parser)
activate ":HelpMenuManager"
":HelpMenuManager" -> HelpValidator: validateCommand()

@enduml