@startuml SequenceDiagram

skinparam classAttributeIconSize 0
skinparam style strictuml
participant User
participant Parser
participant WorkoutManager
participant Workout
participant ActivityManager

User -> Parser: Inputs command 'workout /create push_day'
Parser -> WorkoutManager: Parse command
activate WorkoutManager
WorkoutManager -> WorkoutManager: Validate input to ensure correct command format
alt Input validation successful
    WorkoutManager -> Workout: Create new Workout object with name 'push_day'
    activate Workout
    WorkoutManager -> ActivityManager: Invoke add method to add workout to activitySet
    activate ActivityManager
    ActivityManager -> Workout: Adds workout to activitySet
    deactivate ActivityManager
    deactivate Workout
    WorkoutManager -> User: Print success message
    deactivate WorkoutManager
else Input validation fails
    WorkoutManager -> User: Print error message indicating invalid command format
end

@enduml
