@startuml SequenceDiagram

skinparam classAttributeIconSize 0
skinparam style strictuml

participant ByteCeps as User
participant UserInterface
participant ":ActivityManager" as ActivityManager
participant ":Parser" as Parser
participant ":WorkoutManager" as WorkoutManager
participant ":WorkoutValidator" as Validator
participant ":ExerciseManager" as ExerciseManager
participant ":Exercise" as Exercise
participant ":Workout" as Workout

User -> Parser : parseInput(userInput)
activate Parser
User <-- Parser
deactivate Parser

User -> WorkoutManager : execute(parser)
activate WorkoutManager

WorkoutManager -> Validator : validateCommand(Parser)
activate Validator
Validator --> WorkoutManager : Validation success
deactivate Validator

alt Validation successful

    WorkoutManager -> WorkoutManager : executeAssignAction(Parser)
    activate WorkoutManager #FFBBBB

    WorkoutManager -> ExerciseManager : retrieve('Pushups')
    activate ExerciseManager
    create ":ActivityManager" as ActivityManager
    ExerciseManager -> ActivityManager : retrieve('Pushups')
    activate ActivityManager

    ActivityManager -> Exercise : findByName('Pushups')
    activate Exercise
    Exercise --> ActivityManager : return existingExercise
    deactivate Exercise

    ActivityManager --> ExerciseManager : return existingExercise
    deactivate ActivityManager
    ExerciseManager --> WorkoutManager : return existingExercise
    deactivate ExerciseManager

    WorkoutManager -> ActivityManager : retrieve('LegDay')
    activate ActivityManager
    ActivityManager -> Workout : findByName('LegDay')
    activate Workout

    Workout --> ActivityManager : return existingWorkout
    deactivate Workout
    ActivityManager --> WorkoutManager : return existingWorkout
    deactivate ActivityManager

    WorkoutManager -> Workout : addExercise(existingExercise)
    activate Workout
    Workout --> WorkoutManager :
    deactivate Workout

    WorkoutManager --> WorkoutManager : return messageToUser
    deactivate WorkoutManager #FFBBBB
    WorkoutManager --> User : messageToUser

    User -> UserInterface: printMessage(messageToUser)
    activate UserInterface
    UserInterface --> User
    deactivate UserInterface

    destroy Workout
    destroy Exercise
    destroy ActivityManager

else Validation fails
    User -> UserInterface: printMessage(exceptionMessage : String)
    activate UserInterface
    UserInterface --> User:
    deactivate UserInterface
end

deactivate WorkoutManager
deactivate Parser

@enduml
