@startuml SequenceDiagram
skinparam classAttributeIconSize 0
skinparam style strictuml

participant ByteCeps
participant UserInterface
participant ":Parser"
participant ":WeeklyProgramManager"
participant WeeklyProgramValidator
participant ":WorkoutManager"

ByteCeps -> ":Parser": parseInput(userInput)
activate ":Parser"
ByteCeps <-- ":Parser":
deactivate ":Parser"
ByteCeps -> ":WeeklyProgramManager": execute(parser)
activate ":WeeklyProgramManager"
":WeeklyProgramManager" -> WeeklyProgramValidator: validateCommand(parser)

activate WeeklyProgramValidator
":WeeklyProgramManager" <-- WeeklyProgramValidator :
deactivate WeeklyProgramValidator

alt Input validation successful
    ":WeeklyProgramManager" -> ":WeeklyProgramManager": executeAssignAction(parser)
    activate ":WeeklyProgramManager"
    ":WeeklyProgramManager" -> ":WorkoutManager": retrieve(workoutName)
    activate ":WorkoutManager"
    ":WorkoutManager" --> ":WeeklyProgramManager": workout
    deactivate ":WorkoutManager"
    ":WeeklyProgramManager" -> ":WeeklyProgramManager" : assignWorkoutToDay(workout, day)
    activate ":WeeklyProgramManager"
    ":WeeklyProgramManager" --> ":WeeklyProgramManager" : messageToUser
    deactivate ":WeeklyProgramManager"
    ":WeeklyProgramManager" --> ":WeeklyProgramManager": messageToUser
    deactivate ":WeeklyProgramManager"
    ":WeeklyProgramManager" --> ByteCeps : messageToUser
    ByteCeps -> UserInterface: printMessage(messageToUser)
    activate UserInterface
    UserInterface --> ByteCeps :
    deactivate UserInterface
else Input validation fails
    ":WeeklyProgramManager" --> ByteCeps:
    deactivate ":WeeklyProgramManager"
    ByteCeps -> UserInterface: printMessage(exceptionMessage)
    activate UserInterface
    UserInterface --> ByteCeps:
    deactivate UserInterface
end
deactivate WeeklyProgramValidator
@enduml
