@startuml SequenceDiagram
skinparam classAttributeIconSize 0
skinparam style strictuml

participant ByteCeps
participant ":UserInterFace" as UserInterface
participant ":WeeklyProgramManager"

    activate ByteCeps
    ByteCeps -> ":WeeklyProgramManager" : execute(parser)
    activate ":WeeklyProgramManager"
    ":WeeklyProgramManager" -> ":WeeklyProgramManager" : executeClearAction(parser)
    activate ":WeeklyProgramManager"
    alt No specific day specified by user
        ":WeeklyProgramManager" -> ":WeeklyProgramManager" : clearActivitySet()
        activate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ":WeeklyProgramManager":
        deactivate ":WeeklyProgramManager"
        ":WeeklyProgramManager" -> ":WeeklyProgramManager" : initializeDays()
        activate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ":WeeklyProgramManager":
        deactivate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ":WeeklyProgramManager": messageToUser
        deactivate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ByteCeps: messageToUser
    else Specific day entered by user
        ":WeeklyProgramManager" -> ":WeeklyProgramManager" : remove(selectedDay)
        activate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ":WeeklyProgramManager":
        deactivate ":WeeklyProgramManager"
        create Day as ":Day"
        ":WeeklyProgramManager" -> Day : new Day(selectedDayString)
        activate Day
        Day --> ":WeeklyProgramManager" : newDay
        deactivate Day
        ":WeeklyProgramManager" -> Day : setAssignedWorkout(null)
        activate Day
        Day --> ":WeeklyProgramManager" :
        deactivate Day
        ":WeeklyProgramManager" -> ":WeeklyProgramManager" : add(newDay)
        activate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ":WeeklyProgramManager":
        deactivate ":WeeklyProgramManager"
        ":WeeklyProgramManager" --> ByteCeps: messageToUser
        deactivate ":WeeklyProgramManager"
    end

    ByteCeps -> UserInterface: printMessage(messageToUser)
    activate UserInterface
    UserInterface --> ByteCeps :
    deactivate UserInterface


@enduml
