@startuml SequenceDiagram

skinparam classAttributeIconSize 0
skinparam style strictuml

participant ByteCeps as User
participant UserInterface
participant ":Parser" as Parser
participant ":WorkoutManager" as WorkoutManager
participant ":WorkoutValidator" as Validator
participant ":Workout" as Workout

User -> Parser : parseInput(userInput)
activate Parser
User <-- Parser
deactivate Parser

User -> WorkoutManager : execute(parser)
activate WorkoutManager

WorkoutManager -> Validator : validateCommand(Parser)
activate Validator
Validator --> WorkoutManager :
deactivate Validator

alt Validation successful
    WorkoutManager -> WorkoutManager : executeDeleteAction(Parser)
    activate WorkoutManager #FFBBBB

    WorkoutManager -> WorkoutManager : retrieve('LegDay')
    activate WorkoutManager
    WorkoutManager -> Workout : findByName('LegDay')
    activate Workout
    Workout --> WorkoutManager : return existingWorkout
    deactivate Workout
    WorkoutManager --> WorkoutManager : existingWorkout
    deactivate WorkoutManager #FFBBBB

    WorkoutManager -> WorkoutManager : delete(existingWorkout)
    activate WorkoutManager
    WorkoutManager --> WorkoutManager :
    deactivate WorkoutManager


    WorkoutManager --> WorkoutManager : return messageToUser
    deactivate WorkoutManager #FFBBBB
    WorkoutManager --> User : messageToUser
    User -> UserInterface: printMessage(messageToUser)
    activate UserInterface
    UserInterface --> User
    deactivate UserInterface

else Validation fails
    User -> UserInterface: printMessage(exceptionMessage : String)
    activate UserInterface
    UserInterface --> User:
    deactivate UserInterface
end

deactivate WorkoutManager
deactivate Parser

@enduml
