@startuml SequenceDiagram

title List Workouts Sequence Diagram
skinparam classAttributeIconSize 0
skinparam style strictuml
participant User
participant Parser
participant WorkoutManager
participant ActivityManager

User -> Parser: Inputs command 'workout /list'
Parser -> WorkoutManager: Parse command
activate WorkoutManager
WorkoutManager -> WorkoutManager: Validate input to ensure correct command format
alt Input validation successful
    WorkoutManager -> ActivityManager: Invoke list method to retrieve list of workouts from activitySet
    activate ActivityManager
    ActivityManager -> ActivityManager: Retrieve list of workouts from activitySet
    ActivityManager --> WorkoutManager: Returns list of workout plans
    deactivate ActivityManager
    WorkoutManager -> User: Print list of workout plans
    deactivate WorkoutManager
else Input validation fails
    WorkoutManager -> User: Print error message
end

@enduml